repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v17.0.6"
    hooks:
      - id: clang-format
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: "8.2.1"
    hooks:
      - id: buildifier
      - id: buildifier-lint