name: bazel run

on:
  push:
    branches:
      - "master"
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: install clang
        run: sudo apt update && sudo apt install -y clang-20 mold

      - name: unittest
        run: |
          bazel build --config=ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //app:usage

      - name: run-ut
        run: |
          ./bazel-bin/app/usage

      - name: benchmark
        run: |
          bazel build --config=ci --config=opt --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //bench:bench

      - name: run-bm
        run: |
          ./bazel-bin/bench/bench --benchmark_min_time=10s
